version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
        name: install
        command: npm install
      - run:
        name: omg-cli help
        command: "./omg-cli --help"
